export { default as logotipo } from './logotipo.svg'
export { default as logo } from './logo.svg'
export { default as enjoy } from './enjoy.svg'
export { default as card } from './card.svg'
export { default as congratulations } from './congratulations.svg'
